title: Rails 4 App Template
display_name: Rails Template
min_age: 18
max_age: 140
user_form_options: ['name?', 'username?', 'gender?', 'birthdate?', 'time_zone?']
enable_name?: true
require_name?: true
enable_username?: true
require_username?: true
enable_gender?: true
require_gender?: true
enable_birthdate?: true
require_birthdate?: true
enable_time_zone?: true
require_time_zone?: true
verify_email?: true
user_name_field: email_or_username
check_remember_me?: true
password_reset_ttl_hours: 4
development:
  host: "localhost:3000"
test:
  host: "test.local"
production:
  host: "www.ApplicationTemplate.com"